# Checkpoint 에 저장된 Variable 확인 방법

In [1]:
from tensorflow.python.tools import inspect_checkpoint as chkp
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-10000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.9051934   0.6069451  -1.5121312 ]
 [ 2.036335   -0.05406574 -1.982269  ]
 [-2.8306117  -0.10605469  2.9366426 ]
 [-1.3426015  -1.0283835   2.3709831 ]]
tensor_name:  bias
[ 0.43785098  0.6570569  -1.0949075 ]


In [2]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-9000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.8698726   0.59103835 -1.4609058 ]
 [ 1.9658532  -0.0772764  -1.8885783 ]
 [-2.7355802  -0.09272358  2.8282866 ]
 [-1.2951736  -0.97110397  2.2662756 ]]
tensor_name:  bias
[ 0.4221452  0.6053049 -1.0274497]


In [3]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-8000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.8311586   0.57188696 -1.4030417 ]
 [ 1.8882452  -0.10163423 -1.7866116 ]
 [-2.631055   -0.07706007  2.7081027 ]
 [-1.2432513  -0.9086988   2.1519496 ]]
tensor_name:  bias
[ 0.40489718  0.55157894 -0.95647573]


In [4]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-7000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.7883151   0.5485012  -1.3368132 ]
 [ 1.80189    -0.12707624 -1.6748142 ]
 [-2.514901   -0.05841514  2.573308  ]
 [-1.185849   -0.84003097  2.0258796 ]]
tensor_name:  bias
[ 0.3857639   0.49553728 -0.88130087]


In [5]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-2000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.453658    0.2780371  -0.7316954 ]
 [ 1.1051062  -0.25005212 -0.8550553 ]
 [-1.582721    0.13271017  1.4500074 ]
 [-0.73568475 -0.30992246  1.0456067 ]]
tensor_name:  bias
[ 0.23379596  0.15576091 -0.38955677]


In [6]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-1000', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[ 0.32881042  0.14310434 -0.47191474]
 [ 0.82735056 -0.24585205 -0.5814983 ]
 [-1.2066782   0.2042201   1.0024576 ]
 [-0.5589428  -0.12238699  0.6813302 ]]
tensor_name:  bias
[ 0.17442037  0.06590008 -0.24032065]


In [7]:
chkp.print_tensors_in_checkpoint_file('./model/model_20190703_154851.ckpt-0', tensor_name='', all_tensors=True)

tensor_name:  Weight
[[-0.00180318  0.00053016  0.00127302]
 [ 0.00178413 -0.00086349 -0.00092064]
 [-0.00712699  0.00205397  0.00507302]
 [-0.00301905  0.00062857  0.00239048]]
tensor_name:  bias
[ 1.9047617e-04 -1.1641532e-10 -1.9047625e-04]


# Checkpoint 에 마지막 저장된 model 정보 보는 방법

In [8]:
import tensorflow as tf

In [9]:
# 저장된 모델 경로 지정
modelFileName = "model_20190703_154851.ckpt-10000"
save_file = './model/'+modelFileName

print("Loading saved model file : "+save_file)

Loading saved model file : ./model/model_20190703_154851.ckpt-10000


In [10]:
# 지금까지 저장된 변수의 값 리셋 하기
tf.reset_default_graph

<function tensorflow.python.framework.ops.reset_default_graph()>

In [11]:
# Weight 변수 선언
W = tf.Variable(tf.zeros([4, 3]), name='Weight')
# Bias 변수 선언
b = tf.Variable(tf.zeros([3]), name='bias')

In [12]:
# 모델을 불러오기 위하여 saver 객체 선언
saver = tf.train.Saver()

In [13]:
with tf.Session() as sess:
    #sess.run(tf.global_variables_initializer())
    # 저장된 모델 정보를 sess에 가져오기
    saver.restore(sess, save_file)
    print("[Weight]")
    print(sess.run(W))
    print("[Bias]")
    print(sess.run(b))

INFO:tensorflow:Restoring parameters from ./model/model_20190703_154851.ckpt-10000
[Weight]
[[ 0.9051934   0.6069451  -1.5121312 ]
 [ 2.036335   -0.05406574 -1.982269  ]
 [-2.8306117  -0.10605469  2.9366426 ]
 [-1.3426015  -1.0283835   2.3709831 ]]
[Bias]
[ 0.43785098  0.6570569  -1.0949075 ]


# 모델 그래프를 불러와서 사용 가능한 operation 항목 확인

In [14]:
# 지금까지 저장된 변수의 값 리셋 하기
tf.reset_default_graph

<function tensorflow.python.framework.ops.reset_default_graph()>

In [15]:
import tensorflow as tf


sess=tf.Session()    
#First let's load meta graph and restore weights
saver = tf.train.import_meta_graph('./model/model_20190703_154851.ckpt-10000.meta')
saver.restore(sess,tf.train.latest_checkpoint('./model/'))

graph = tf.get_default_graph()


for op in tf.get_default_graph().get_operations():
    print(op.name)   

INFO:tensorflow:Restoring parameters from ./model/model_20190703_154851.ckpt-10000
zeros
Weight
Weight/Assign
Weight/read
zeros_1
bias
bias/Assign
bias/read
save/Const
save/SaveV2/tensor_names
save/SaveV2/shape_and_slices
save/SaveV2
save/control_dependency
save/RestoreV2/tensor_names
save/RestoreV2/shape_and_slices
save/RestoreV2
save/Assign
save/Assign_1
save/restore_all
X
Y
zeros_2
Weight_1
Weight/Assign_1
Weight/read_1
zeros_1_1
bias_1
bias/Assign_1
bias/read_1
save/Const_1
save/SaveV2/tensor_names_1
save/SaveV2/shape_and_slices_1
save/SaveV2_1
save/control_dependency_1
save/RestoreV2/tensor_names_1
save/RestoreV2/shape_and_slices_1
save/RestoreV2_1
save/Assign_2
save/Assign_1_1
save/restore_all_1
MatMul
add
hypothesis
Log
mul
Sum/reduction_indices
Sum
Neg
Const
costFunction
gradients/Shape
gradients/grad_ys_0
gradients/Fill
gradients/costFunction_grad/Reshape/shape
gradients/costFunction_grad/Reshape
gradients/costFunction_grad/Shape
gradients/costFunction_grad/Tile
gradients/cost

# 저장된 모델의 마지막 체크포인트 경로

In [16]:
ckpt_path = tf.train.latest_checkpoint('./model/')
print(ckpt_path)

./model/model_20190703_154851.ckpt-10000
